[package]
name = "pkgcraft-bash"
version = "0.0.1"
description = "Bash builtins for pkgcraft"
authors = ["Tim Harder <radhermit@gmail.com>"]
homepage = "https://github.com/pkgcraft/pkgcraft-bash"
repository = "https://github.com/pkgcraft/pkgcraft-bash"
readme = "README.md"
license = "GPL-3"
edition = "2021"
rust-version = "1.60"
autotests = false

[lib]
crate-type = ["cdylib"]

[dependencies]
scallop = { path = "../scallop", version = "0.0.1", features = ["shared"] }
