name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: ['1.65.0', 'stable']

    steps:
    - name: Checkout scallop
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/scallop
        path: scallop
        submodules: true

    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft
        submodules: true

    - name: Checkout pkgcraft-bash
      uses: actions/checkout@v3
      with:
        path: pkgcraft-bash
        submodules: true

    - name: Get bash submodule status
      working-directory: scallop/bash
      run: echo "SCALLOP_BASH=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      id: rust
      with:
        toolchain: ${{ matrix.rust-version }}

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}-cargo-${{ hashFiles('pkgcraft-bash/Cargo.lock') }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Various macos set up
      if: runner.os == 'macOS'
      run: |
        # force using clang as a C compiler
        echo "CC=clang" >> $GITHUB_ENV
        echo "CFLAGS=-arch x86_64" >> $GITHUB_ENV
        # install newer bash -- macos defaults to ancient bash due to licensing
        brew install bash

    - name: Build builtins
      run: |
        # first build with default features enabled
        cargo build --manifest-path=pkgcraft-bash/Cargo.toml --target-dir target
        # then with all features enabled
        cargo build --all-features --manifest-path=pkgcraft-bash/Cargo.toml --target-dir target
        # export variables required to run tests
        echo "CARGO_BUILD_DIR=${PWD}/target/debug" >> $GITHUB_ENV

    - name: Output bash info
      run: bash --version

    - name: Install bats test framework
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.7.0

    - name: Run tests
      working-directory: pkgcraft-bash
      run: bats -r tests

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout scallop
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/scallop
        path: scallop
        submodules: true

    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft
        submodules: true

    - name: Checkout pkgcraft-bash
      uses: actions/checkout@v3
      with:
        path: pkgcraft-bash
        submodules: true

    - name: Get bash submodule status
      working-directory: scallop/bash
      run: echo "SCALLOP_BASH=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust
      with:
        components: clippy, rustfmt

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}-cargo-${{ hashFiles('pkgcraft-bash/Cargo.lock') }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Run rustfmt
      run: cargo fmt --check --manifest-path=pkgcraft-bash/Cargo.toml

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path=pkgcraft-bash/Cargo.toml --target-dir target
