name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust-version: ['1.60.0', 'stable']

    steps:
    - name: Checkout scallop
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/scallop
        path: scallop
        submodules: true

    - name: Move scallop into expected location
      run: mv scallop ../

    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Move pkgcraft into expected location
      run: mv pkgcraft ../

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up rust toolchain
      uses: actions-rs/toolchain@v1
      id: rust
      with:
        toolchain: ${{ matrix.rust-version }}
        profile: minimal
        override: true

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: v2-${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.rustc_hash }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: v2-${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.rustc_hash }}-cargo-

    - name: Update deps
      run: cargo update

    - name: Install meson
      run: sudo pip3 install meson

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Various macos set up
      if: matrix.os == 'macos-latest'
      run: |
        # force using clang as a C compiler
        echo "CC=clang" >> $GITHUB_ENV
        echo "CFLAGS=-arch x86_64" >> $GITHUB_ENV

    - name: Build builtins
      run: |
        # first build with default features enabled
        cargo build
        # then with all features enabled
        cargo build --all-features
